language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
bundler_args: --without development
script:
  - bundle exec rake spec
gemfile:
  - gemfiles/gemfile.1.8.7
  - gemfiles/gemfile.1.9.3

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/gemfile.1.9.3
    - rvm: 1.9.3
      gemfile: gemfiles/gemfile.1.8.7
    - rvm: 2.0.0
      gemfile: gemfiles/gemfile.1.8.7
