language: ruby
rvm:
  - 1.8.7
  - 1.9.3
bundler_args: --without development
before_install:
  -  gem update --system 2.1.11
script: bundle exec rspec spec
notifications:
  email:
    - biemond@gmail.com
env:
  - PUPPET_VERSION=2.7.24
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.4.1